name: Update gist with WakaTime stats

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    name: Update-gist
    runs-on: ubuntu-latest
    env:
      WAKATIME_API_KEY: dedff469-ac40-4e55-92be-07c0c69f0948
      GH_TOKEN: 4bf869703f306ff9f307f8ea29d5a5921e8bbd2c
      GIST_ID: 82112fc141f1d6ff764884aa0fbca2bc
      GIST_BARSTYLE: SOLIDLT
      GIST_BARLENGTH: -1
      GIST_TIMESTYLE: SHORT

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Update-gist
        run: go run ./cmd/box/main.go
